"""empty message

Revision ID: b0dc334ea9fd
Revises: c903a2b1d2e0
Create Date: 2020-10-30 19:26:37.907197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0dc334ea9fd'
down_revision = 'c903a2b1d2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('president', sa.String(length=50), nullable=False))
    op.add_column('club', sa.Column('teacher', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club', 'teacher')
    op.drop_column('club', 'president')
    # ### end Alembic commands ###
